IF OBJECT_ID('BOOK_COPY', 'U') IS NOT NULL
    DROP TABLE BOOK_COPY;

IF OBJECT_ID('LIBRARIAN', 'U') IS NOT NULL
    DROP TABLE LIBRARIAN;

IF OBJECT_ID('BOOK', 'U') IS NOT NULL
    DROP TABLE BOOK;

IF OBJECT_ID('FINES', 'U') IS NOT NULL
    DROP TABLE FINES;

IF OBJECT_ID('BORROWING_TRANSACTION', 'U') IS NOT NULL
    DROP TABLE BORROWING_TRANSACTION;

IF OBJECT_ID('MEMBER', 'U') IS NOT NULL
    DROP TABLE MEMBER;

IF OBJECT_ID('LIBRARY_BRANCH', 'U') IS NOT NULL
    DROP TABLE LIBRARY_BRANCH;

CREATE TABLE LIBRARY_BRANCH(
    BRANCH_ID CHAR(5) NOT NULL,
    BRANCH_NAME VARCHAR(50) NOT NULL UNIQUE,
    ADDRESS VARCHAR(100),
    PHONE VARCHAR(15),
    PRIMARY KEY (BRANCH_ID)
);

CREATE TABLE MEMBER(
    MEMBER_ID CHAR(6),
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    PHONE VARCHAR(15),
    JOIN_DATE DATE,
    MEMBERSHIP_STATUS CHAR(1),
    PRIMARY KEY (MEMBER_ID),
    CONSTRAINT CHK_STATUS CHECK (MEMBERSHIP_STATUS IN ('A', 'I'))
);

CREATE TABLE BOOK(
    ISBN CHAR(13),
    TITLE VARCHAR(100) NOT NULL,
    AUTHOR VARCHAR(50),
    PUBLISHER VARCHAR(50),
    YEAR_PUBLISHED INT,
    CATEGORY VARCHAR(30),
    TOTAL_COPIES INT DEFAULT 1,
    PRIMARY KEY (ISBN),
    CONSTRAINT CHK_YEAR_PUB CHECK (YEAR_PUBLISHED BETWEEN 1900 AND 2026)
);

CREATE TABLE LIBRARIAN(
    LIBRARIAN_ID CHAR(5),
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    BRANCH_ID CHAR(5),
    HIRE_DATE DATE,
    SALARY NUMERIC(10,2),
    PRIMARY KEY(LIBRARIAN_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES LIBRARY_BRANCH(BRANCH_ID),
    CONSTRAINT CHK_LIBRARY_SAL_POS  CHECK (SALARY > 0)
);

CREATE TABLE BOOK_COPY(
    COPY_ID INT IDENTITY(1,1) NOT NULL,
    ISBN CHAR(13) NOT NULL,
    BRANCH_ID CHAR(5) NOT NULL,
    COPY_NUMBER INT UNIQUE,
    CONDITION VARCHAR(20),
    AVAILABLE CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (BRANCH_ID, COPY_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES LIBRARY_BRANCH(BRANCH_ID),
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN),
    CONSTRAINT CHK_CONDITION CHECK (CONDITION IN ('Excellent', 'Good', 'Fair', 'Poor')),
    CONSTRAINT CHK_AVAIL CHECK (AVAILABLE IN ('Y', 'N'))
);

CREATE TABLE BORROWING_TRANSACTION(
    TRANSACTION_ID INT IDENTITY(1,1) NOT NULL, /*INCREMENTS BY 1*/
    MEMBER_ID CHAR(6) NOT NULL,
    COPY_ID INT NOT NULL,
    CHECKOUT_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    RETURN_DATE DATE NOT NULL,
    STATUS CHAR(1),
    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT CHK_STATUS_BORROWING CHECK (STATUS IN ('O', 'R', 'L'))
)

CREATE TABLE FINES(
    FINE_ID INT IDENTITY(1,1) NOT NULL,
    TRANSACTION_ID INT, 
    FINE_AMOUNT NUMERIC(8,2),
    DATE_ISSUED DATE,
    DATE_PAID DATE,
    PAID_STATUS CHAR(1),
    PRIMARY KEY (FINE_ID),
    FOREIGN KEY (TRANSACTION_ID) REFERENCES BORROWING_TRANSACTION(TRANSACTION_ID),
    CONSTRAINT CHK_FINE_AMOUNT CHECK (FINE_AMOUNT > 0),
    CONSTRAINT CHK_PAID_STATUS CHECK (PAID_STATUS IN ('P', 'U'))
);

ALTER TABLE MEMBER ADD DATE_OF_BIRTH DATE;
ALTER TABLE MEMBER ADD BORROWING_LIMIT INT;

GO
ALTER TABLE MEMBER ADD CONSTRAINT CHK_BORROWING_LIMIT CHECK 
    (BORROWING_LIMIT BETWEEN 1 AND 10);

ALTER TABLE MEMBER ADD CONSTRAINT CHK_EMAIL_NOT_NULL CHECK (EMAIL IS NOT NULL);

ALTER TABLE BOOK ADD GENRE VARCHAR(30) DEFAULT 'GENERAL';

ALTER TABLE BOOK DROP CONSTRAINT CHK_YEAR_PUB;
ALTER TABLE BOOK ADD CONSTRAINT CHK_PUBLISH_YEAR CHECK 
    (YEAR_PUBLISHED BETWEEN 1800 AND 2026);

GO
IF OBJECT_ID('ACTIVE_MEMBERS', 'V') IS NOT NULL
    DROP VIEW ACTIVE_MEMBERS;

GO

CREATE VIEW ACTIVE_MEMBERS AS 
SELECT
    MEMBER_ID,
    FIRST_NAME + ' ' + LAST_NAME AS FULL_NAME,
    EMAIL,
    PHONE,
    JOIN_DATE 
FROM MEMBER
WHERE MEMBERSHIP_STATUS = 'A';

GO

IF OBJECT_ID('OVERDUE_BOOKS', 'V') IS NOT NULL
    DROP VIEW OVERDUE_BOOKS

GO

CREATE VIEW OVERDUE_BOOKS AS
SELECT
    BT.TRANSACTION_ID,
    BT.MEMBER_ID,
    M.FIRST_NAME + ' ' + M.LAST_NAME AS FULL_NAME,
    B.TITLE,
    BT.CHECKOUT_DATE,
    BT.DUE_DATE,
    DATEDIFF(DAY, BT.DUE_DATE, GETDATE()) AS DAYS_OVERDUE
FROM BORROWING_TRANSACTION BT 
JOIN MEMBER M ON BT.MEMBER_ID = M.MEMBER_ID
JOIN BOOK_COPY BC ON BT.COPY_ID = BC.COPY_ID 
JOIN BOOK B ON BC.ISBN = B.ISBN
WHERE STATUS = 'L' OR (BT.DUE_DATE < GETDATE() AND BT.RETURN_DATE IS NULL);



