IF OBJECT_ID('BOOK_COPY', 'U') IS NOT NULL
    DROP TABLE BOOK_COPY;

IF OBJECT_ID('LIBRARIAN', 'U') IS NOT NULL
    DROP TABLE LIBRARIAN;

IF OBJECT_ID('BOOK', 'U') IS NOT NULL
    DROP TABLE BOOK;

IF OBJECT_ID('MEMBER', 'U') IS NOT NULL
    DROP TABLE MEMBER;

IF OBJECT_ID('LIBRARY_BRANCH', 'U') IS NOT NULL
    DROP TABLE LIBRARY_BRANCH;

CREATE TABLE LIBRARY_BRANCH(
    BRANCH_ID CHAR(5) NOT NULL,
    BRANCH_NAME VARCHAR(50) NOT NULL UNIQUE,
    ADDRESS VARCHAR(100),
    PHONE VARCHAR(15),
    PRIMARY KEY (BRANCH_ID)
);

CREATE TABLE MEMBER(
    MEMBER_ID CHAR(6),
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    PHONE VARCHAR(15),
    JOIN_DATE DATE,
    MEMBERSHIP_STATUS CHAR(1),
    PRIMARY KEY (MEMBER_ID),
    CONSTRAINT CHK_STATUS CHECK (MEMBERSHIP_STATUS IN ('A', 'I'))
);

CREATE TABLE BOOK(
    ISBN CHAR(13),
    TITLE VARCHAR(100) NOT NULL,
    AUTHOR VARCHAR(50),
    PUBLISHER VARCHAR(50),
    YEAR_PUBLISHED INT,
    CATEGORY VARCHAR(30),
    TOTAL_COPIES INT DEFAULT 1,
    PRIMARY KEY (ISBN),
    CONSTRAINT CHK_YEAR_PUB CHECK (YEAR_PUBLISHED BETWEEN 1900 AND 2026)
);

CREATE TABLE LIBRARIAN(
    LIBRARIAN_ID CHAR(5),
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    BRANCH_ID CHAR(5),
    HIRE_DATE DATE,
    SALARY NUMERIC(10,2),
    PRIMARY KEY(LIBRARIAN_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES LIBRARY_BRANCH(BRANCH_ID),
    CONSTRAINT CHK_LIBRARY_SAL_POS  CHECK (SALARY > 0)
);

CREATE TABLE BOOK_COPY(
    COPY_ID INT,
    ISBN CHAR(13),
    BRANCH_ID CHAR(5),
    COPY_NUMBER INT UNIQUE,
    CONDITION VARCHAR(20),
    AVAILABLE CHAR(1),
    PRIMARY KEY (BRANCH_ID, COPY_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES LIBRARY_BRANCH(BRANCH_ID),
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN),
     
);