IF OBJECT_ID('REGISTRATION', 'U') IS NOT NULL
  DROP TABLE REGISTRATION;

IF OBJECT_ID('ENROLLMENT', 'U') IS NOT NULL
  DROP TABLE ENROLLMENT;

IF OBJECT_ID('ASSIGNMENT', 'U') IS NOT NULL
  DROP TABLE ASSIGNMENT;

IF OBJECT_ID('PROJECT', 'U') IS NOT NULL
  DROP TABLE PROJECT;

IF OBJECT_ID('BOOKS', 'U') IS NOT NULL
	DROP TABLE BOOKS;
  
IF OBJECT_ID('STUDENT', 'U') IS NOT NULL
  DROP TABLE STUDENT;

IF OBJECT_ID('COURSE', 'U') IS NOT NULL 
  DROP TABLE COURSE;

IF OBJECT_ID('DEPARTMENT', 'U') IS NOT NULL 
  DROP TABLE DEPARTMENT;

IF OBJECT_ID('EMPLOYEE', 'U') IS NOT NULL
  DROP TABLE EMPLOYEE;



CREATE TABLE BOOKS(
  BOOK_ID CHAR(5) NOT NULL,
  TITLE VARCHAR(100),
  AUTHOR VARCHAR(50),
  YEAR_PUBLISHED INT,
  PRICE NUMERIC(8,2),
  PRIMARY KEY (BOOK_ID)
);


CREATE TABLE ENROLLMENT(
  STUDENT_ID CHAR(6) NOT NULL,
  COURSE_CODE CHAR(8) NOT NULL,
  SEMESTER CHAR(6) NOT NULL, 
  GRADE CHAR(2),
  ENROLLMENT_DATE DATE,
  PRIMARY KEY (STUDENT_ID, COURSE_CODE, SEMESTER)
);

CREATE TABLE STUDENT(
  STUDENT_ID CHAR(6) NOT NULL,
  FIRST_NAME VARCHAR(30),
  LAST_NAME VARCHAR(30),
  MAJOR VARCHAR(30),
  GPA NUMERIC (3,2),
  PRIMARY KEY (STUDENT_ID)
);
  
CREATE TABLE COURSE(
  COURSE_ID CHAR(6) NOT NULL,
  COURSE_NAME VARCHAR(50),
  CREDITS INT,
  INSTRUCTOR VARCHAR(40),
  PRIMARY KEY (COURSE_ID)
);

CREATE TABLE REGISTRATION(
  STUDENT_ID CHAR(6) NOT NULL,
  COURSE_ID CHAR(6) NOT NULL,
  REG_DATE DATE,
  GRADE CHAR(2),
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

CREATE TABLE DEPARTMENT(
  DEPT_CODE CHAR(4),
  DEPT_NAME VARCHAR(40) UNIQUE,
  MANAGER_ID CHAR(6) NOT NULL,
  BUDGET NUMERIC(10,2),
  LOCATION VARCHAR(30),
  PRIMARY KEY (DEPT_CODE)
 );

CREATE TABLE EMPLOYEE(
  EMP_ID CHAR(5),
  EMP_NAME VARCHAR(40) NOT NULL,
  AGE INT,
  SALARY NUMERIC(10,2),
  GENDER CHAR(1),
  EMAIL VARCHAR(50) UNIQUE,
  CONSTRAINT CHK_AGE CHECK (AGE BETWEEN 18 AND 65),
  CONSTRAINT CHK_SAL CHECK (SALARY > 0),
  CONSTRAINT CHECK_GEN CHECK (GENDER IN ('M', 'F')),
  PRIMARY KEY (EMP_ID)
);

CREATE TABLE PROJECT(
  PROJECT_ID CHAR(5),
  PROJECT_NAME VARCHAR(50) NOT NULL,
  START_DATE DATE,
  PRIMARY KEY (PROJECT_ID)
);

CREATE TABLE ASSIGNMENT(
  EMP_ID CHAR(5),
  PROJECT_ID CHAR(5),
  HOURS_WORKED NUMERIC(5,2),
  PRIMARY KEY (EMP_ID, PROJECT_ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID) ON DELETE CASCADE  /*what does this mean, how does it work*/
);


